// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1MADHEih7cUcc1ww2S0rqIIDuSz-2z-A',
    appId: '1:928210968988:web:3d5e3d041d3b32d35f6859',
    messagingSenderId: '928210968988',
    projectId: 'agri-rent-66546',
    authDomain: 'agri-rent-66546.firebaseapp.com',
    storageBucket: 'agri-rent-66546.firebasestorage.app',
    measurementId: 'G-VS008CQLB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_jQL08QW02ZjjwBsq8UgvmVRA1goP7bQ',
    appId: '1:928210968988:android:6f950d0fcbc8a0985f6859',
    messagingSenderId: '928210968988',
    projectId: 'agri-rent-66546',
    storageBucket: 'agri-rent-66546.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqv8M-n4AvPt0VMDcLJjKSx8OTr07C2d4',
    appId: '1:928210968988:ios:3c24625400bb5c985f6859',
    messagingSenderId: '928210968988',
    projectId: 'agri-rent-66546',
    storageBucket: 'agri-rent-66546.firebasestorage.app',
    iosBundleId: 'com.example.agriRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqv8M-n4AvPt0VMDcLJjKSx8OTr07C2d4',
    appId: '1:928210968988:ios:3c24625400bb5c985f6859',
    messagingSenderId: '928210968988',
    projectId: 'agri-rent-66546',
    storageBucket: 'agri-rent-66546.firebasestorage.app',
    iosBundleId: 'com.example.agriRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1MADHEih7cUcc1ww2S0rqIIDuSz-2z-A',
    appId: '1:928210968988:web:5d697a8d62ff8fa15f6859',
    messagingSenderId: '928210968988',
    projectId: 'agri-rent-66546',
    authDomain: 'agri-rent-66546.firebaseapp.com',
    storageBucket: 'agri-rent-66546.firebasestorage.app',
    measurementId: 'G-B8GNQXZSNG',
  );
}
